### PR TITLE
BUGFIX: adjust cache config to make pagination work

### PR DESCRIPTION
**Pull request by mkuiphuis**
As discussed with Dmitry on Slack... the proposed changes make page navigation work again

### CODE REVIEW

**Comment by dimaip** [comment]
Hey, thanks for taking care!
I think it would be better if you move this part to root.ts2:

```
prototype(TYPO3.Neos:ContentCollection).@cache.entryIdentifier.pagination = ${request.pluginArguments.listable-paginate.currentPage}
prototype(TYPO3.Neos:Page).@cache.entryIdentifier.pagination = ${request.pluginArguments.listable-paginate.currentPage}
root.@cache.entryIdentifier.pagination = ${request.pluginArguments.listable-paginate.currentPage}
```

**Comment by dimaip** [comment]
Hey but I still don't see the changes to root.ts2...

**Comment by mkuiphuis** [comment]
I thought you meant the Root.ts2 in my own site package and not the Root.ts2 of the news package. I'll probably close this pull request and start a new one....

**Comment by dimaip** [comment]
Oh no no, I totally makes sense to put it into the package, it belongs there, just in the root.ts2, to make it more visible

**Comment by dimaip** [comment]
Perfect, thanks!

**Pull request merged**
